title: "Viet-Man Le"
tagline: "Researcher in Knowledge-Based AI | PhD Candidate at TU Graz | Open-Source Developer"
url: "https://manleviet.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-104489558-5

favicon: true
favicon_location: favicon.ico

footer: true
footer_url: "https://github.com/manleviet"
footer_copyright: "©2026"
footer_text: "Viet-Man Le"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "/research.html"
 - name: "Publications"
   link: "/publications.html"
 - name: "Service"
   link: "/service.html"
 - name: "Teaching"
   link: "/teaching.html"
 - name: "Awards & Grants"
   link: "/awards.html"
 - name: "CV"
   link: "/cv.pdf"
