title: Projects
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://projects.manleviet.info

aux_links:
    manleviet on GitHub: https://github.com/manleviet

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
